from __future__ import annotations

from slack_agent.files.parser import parse_docx_bytes, parse_pdf_bytes
from slack_agent.generators.docx import generate_docx_bytes
from slack_agent.generators.pdf import generate_pdf_bytes


def test_generate_pdf_bytes_and_parse_roundtrip() -> None:
    title = "Executive Summary"
    content = "This is a detailed analysis generated by the Slack AI agent."

    result = generate_pdf_bytes(title, content)
    assert result.is_success is True

    pdf_bytes = result.value()
    assert pdf_bytes.startswith(b"%PDF-")
    assert len(pdf_bytes) > 500

    parsed = parse_pdf_bytes(pdf_bytes)
    assert parsed.is_success is True
    assert "Executive Summary" in parsed.value()


def test_generate_docx_bytes_and_parse_roundtrip() -> None:
    title = "System Architecture Report"
    content = (
        "Architecture consists of LangGraph agent, Slack Bolt, and ReportLab.\n\n"
        "All components are strictly typed."
    )

    result = generate_docx_bytes(title, content)
    assert result.is_success is True

    docx_bytes = result.value()
    assert len(docx_bytes) > 500

    parsed = parse_docx_bytes(docx_bytes)
    assert parsed.is_success is True
    assert "System Architecture Report" in parsed.value()
    assert "All components are strictly typed." in parsed.value()
